# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
