# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('mood', models.IntegerField(choices=[(4, 'VeryGood'), (3, 'Good'), (2, 'Bad'), (1, 'VeryBad')])),
                ('content', models.TextField(blank=True, max_length=400)),
                ('post_photo', models.ImageField(blank=True, upload_to='post')),
                ('is_visible', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
