# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ('created_date',)},
        ),
        migrations.RenameField(
            model_name='mood',
            old_name='created_time',
            new_name='created_date',
        ),
    ]
