# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170414_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mood_chk',
            new_name='mood',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mood_comment',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
