# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170401_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='votes',
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood_chk',
            field=models.IntegerField(choices=[(1, 'VeryBad'), (2, 'Bad'), (3, 'Good'), (4, 'VeryGood')]),
        ),
    ]
